### ISSUE TITLE
1.3.9dev CSS is not being delivered by the style service

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3263]
local host environment wampserver, new install. Installed shopp 1.3.8, no issues, functions normally
Replace 1.3.8 with latest 1.3.9 dev and Shopp back end is broken, every page has peculiarities here is the Orders page http://awesomescreenshot.com/0854nqn385

Here is my phpinfo http://awesomescreenshot.com/0924nqgb6e

The shop works OK, just looks off, storefront and back end

**Comment by sierrab123** [comment]
I have now tested on xampp, still acting odd across 3 sites. Reverting to 1.3.8 on all 3 sites cured all issues. Issues such as no Orders appearing on the orders page although the number of orders is shown.

**Comment by jonathandavis** [comment]
This report conflates two separate issues.

The first issue, the style server not working is likely a result of configuration. The orders not appearing are clearly a fatal error (a regression) introduced with changes to fix #3256.

I will fix the fatal error as an extra fix on #3256. For the time being we need to keep this issue open while we diagnose the troubled style server issue.

**Comment by sierrab123** [comment]
can confirm the fix for #3256 works, I downloaded the latest dev this am.
I recall another issue with styles a while back when I was testing the admin orders branch a while back, again the styles would not load for the orders page in that instance. That was on xampp 1.81

It should be noted though that both xampp and wamp work perfectly well with 1.3.8

**Comment by jonathandavis** [comment]
There were several PRs merged in that were branched from `master` not the `1.3.x` branch, so it brought `master` branch changes into `1.3.x`.

**Comment by jonathandavis** [comment]
Perhaps we need to start re-thinking our branch strategy.

**Comment by jonathandavis** [comment]
Fixed by reverting the original PR merge (9a5e5feaec02a0d92497f8490fcf3817de9c1946) and cherry-picking the original change (a6099dffd793e82a285c6a3521ad1383c922485e).

**Comment by sierrab123** [comment]
This is going to make me popular.....! I am having the same issue as was witnessed yesterday by JD, I cloned the 1.3 and replaced my current 1.3, same issues in the admin.I did this twice to make sure. I checked in Chrome as I had not used that to look at the admin before, same problem.

**Comment by sierrab123** [comment]
Several activations and reinstalls later, style server is working on wamp. Permalinks still an issue
